version: '3'

services:
  mysql:
    container_name: muzyka4zycie_mysql
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    ports:
      - 3306:3306
    volumes:
      -  ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      MYSQL_USER: muzyka4zycie_admin
      MYSQL_PASSWORD: muzyka4zycie_password
      MYSQL_DATABASE: muzyka4zycie
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"

  php_app:
    container_name: muzyka4zycie_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - 8080:80
#    volumes:
#      - ./Php:/srv/app
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: muzyka4zycie
      DB_USER: muzyka4zycie_admin
      DB_PASSWORD: muzyka4zycie_password
      SHOP_URL_FRONT: http://localhost:8081

  dotnet_app:
    container_name: muzyka4zycie_dotnet
    build:
      context: .
      dockerfile: docker/dotnet/Dockerfile
    ports:
      - 8081:80
    depends_on:
      - mysql